/**
 * Human-readable artifact rendering for the Agent-Efficiency protocol.
 *
 * The JSON artifact (written verbatim by the runner) is the machine
 * source of truth; this module renders the `.md` summary table and the
 * `--compare` diff table.
 */
import type { Baseline, CompareRow } from './types.js';
import { overallVerdict } from './stats.js';

function usd(n: number): string {
  return `$${n.toFixed(4)}`;
}

function pct(fraction: number): string {
  return `${(fraction * 100).toFixed(1)}%`;
}

function int(n: number): string {
  return Math.round(n).toLocaleString('en-US');
}

function meanSpread(mean: number, stddev: number, fmt: (n: number) => string): string {
  return stddev > 0 ? `${fmt(mean)} ±${fmt(stddev)}` : fmt(mean);
}

/** Render the baseline `.md` summary table. */
export function renderBaselineMarkdown(b: Baseline): string {
  const lines: string[] = [];
  lines.push(`# Agent-Efficiency Baseline — ${b.capturedAt}`);
  lines.push('');
  lines.push('Phase 0 measurement artifact for `PRD-AGENT-EFFICIENCY.md` §6.');
  lines.push('Generated by `scripts/agent-efficiency/measure.ts` — do not hand-edit.');
  lines.push('');
  lines.push(`- **Target:** \`${b.target}\``);
  lines.push(`- **Build:** \`${b.buildSha}\` (engine version \`${b.version}\`)`);
  lines.push(`- **Repeats per scenario (n):** ${b.iterations}`);
  lines.push(`- **Total mean cost across scenarios:** ${usd(b.totalMeanCostUsd)}`);
  lines.push('');
  lines.push('## Per-scenario summary (mean ± sample-stddev across the n repeats)');
  lines.push('');
  lines.push(
    '| Scenario | OK/n | Cost USD | Tokens in | Tokens out | Cache read | Cache write | Cache-hit | Wall |',
  );
  lines.push(
    '|----------|------|----------|-----------|------------|------------|-------------|-----------|------|',
  );
  for (const s of b.scenarios) {
    if (!s.stats) {
      lines.push(
        `| ${s.label} | 0/${s.totalCount} | — | — | — | — | — | — | — |`,
      );
      continue;
    }
    const st = s.stats;
    lines.push(
      `| ${s.label} | ${s.okCount}/${s.totalCount} | ` +
        `${meanSpread(st.costUsd.mean, st.costUsd.stddev, usd)} | ` +
        `${meanSpread(st.tokensIn.mean, st.tokensIn.stddev, int)} | ` +
        `${meanSpread(st.tokensOut.mean, st.tokensOut.stddev, int)} | ` +
        `${meanSpread(st.tokensCacheRead.mean, st.tokensCacheRead.stddev, int)} | ` +
        `${meanSpread(st.tokensCacheWrite.mean, st.tokensCacheWrite.stddev, int)} | ` +
        `${pct(st.cacheHitRatio.mean)} | ` +
        `${(st.wallMs.mean / 1000).toFixed(1)}s |`,
    );
  }
  lines.push('');
  lines.push('## Quality judgement + fidelity notes');
  lines.push('');
  for (const s of b.scenarios) {
    lines.push(`### ${s.label}`);
    lines.push('');
    lines.push(`- **Evidence row:** ${s.evidenceRow}`);
    lines.push(`- **Quality rubric:** ${s.qualityRubric}`);
    if (s.fidelityCaveat) {
      lines.push(`- **Fidelity caveat:** ${s.fidelityCaveat}`);
    }
    const firstOk = s.runs.find((r) => r.ok);
    if (firstOk) {
      const snippet = firstOk.finalText.replace(/\s+/g, ' ').trim().slice(0, 600);
      lines.push(`- **Sample final answer (run 1 OK):** ${snippet || '(empty)'}`);
    }
    const firstErr = s.runs.find((r) => !r.ok);
    if (firstErr) {
      lines.push(`- **Sample failure:** ${firstErr.error ?? 'unknown error'}`);
    }
    lines.push(
      '- **Quality verdict:** _(manual — review the sample answer against the rubric above)_',
    );
    lines.push('');
  }
  return lines.join('\n') + '\n';
}

/** Render the `--compare` diff table. */
export function renderCompareMarkdown(
  baseline: Baseline,
  current: Baseline,
  rows: readonly CompareRow[],
): string {
  const lines: string[] = [];
  lines.push('# Agent-Efficiency Compare');
  lines.push('');
  lines.push(`- **Baseline:** \`${baseline.buildSha}\` captured ${baseline.capturedAt}`);
  lines.push(`- **Current:** \`${current.buildSha}\` captured ${current.capturedAt}`);
  lines.push('');
  lines.push('D3 gate per scenario: pass-rate ≥ baseline AND mean cost < baseline.');
  lines.push('');
  lines.push(
    '| Scenario | Baseline cost | Current cost | Cost Δ% | Token Δ (in) | Pass-rate b→c | Verdict |',
  );
  lines.push(
    '|----------|---------------|--------------|---------|--------------|---------------|---------|',
  );
  for (const r of rows) {
    const bCost = r.baselineCostUsd !== undefined ? usd(r.baselineCostUsd) : '—';
    const cCost = r.currentCostUsd !== undefined ? usd(r.currentCostUsd) : '—';
    const dPct =
      r.costDeltaPct !== undefined
        ? `${r.costDeltaPct >= 0 ? '+' : ''}${(r.costDeltaPct * 100).toFixed(1)}%`
        : '—';
    const dTok =
      r.tokenDelta !== undefined
        ? `${r.tokenDelta >= 0 ? '+' : ''}${int(r.tokenDelta)}`
        : '—';
    lines.push(
      `| ${r.label} | ${bCost} | ${cCost} | ${dPct} | ${dTok} | ` +
        `${pct(r.baselinePassRate)}→${pct(r.currentPassRate)} | ${r.verdict.toUpperCase()} |`,
    );
  }
  lines.push('');
  lines.push(`**Overall D3 gate: ${overallVerdict(rows).toUpperCase()}**`);
  lines.push('');
  return lines.join('\n') + '\n';
}
