import { execFileSync } from 'node:child_process';
import { resolve } from 'node:path';
import { redirectTmpdirForRun, summariseRunRoot } from './test-run-tmpdir.js';

/** packages/web-ui/tsconfig.json extends ./.svelte-kit/tsconfig.json
 *  which is generated by svelte-kit sync. Without it, vite:oxc fails
 *  to transform any web-ui test file. Run sync once before the suite. */
export default function setup(): () => void {
  execFileSync('pnpm', ['exec', 'svelte-kit', 'sync'], {
    cwd: resolve('packages/web-ui'),
    stdio: 'inherit',
  });

  // One temp root for this run, so a fixture that forgets to remove its directory leaks into a
  // directory that goes away instead of into the shared `/tmp`. See `test-run-tmpdir.ts` for why
  // this is a redirect rather than a helper the test files call.
  const runRoot = redirectTmpdirForRun();

  return () => {
    const { entries, removed } = summariseRunRoot(runRoot);
    // Printed, because a number nobody sees is not a measurement: this is how many directories
    // the suite left behind, and it is meant to go DOWN as fixtures are fixed at the source.
    // `removed: false` is the case worth seeing — the root outlived the run.
    console.error(
      `test temp root: ${String(entries)} entr${entries === 1 ? 'y' : 'ies'} left behind` +
        (removed ? '' : ` — AND THE ROOT SURVIVED at ${runRoot}`),
    );
  };
}
