import { execFileSync } from 'node:child_process';
import { resolve } from 'node:path';
import { redirectTmpdirForRun, summariseRunRoot } from './test-run-tmpdir.js';

/** packages/web-ui/tsconfig.json extends ./.svelte-kit/tsconfig.json
 *  which is generated by svelte-kit sync. Without it, vite:oxc fails
 *  to transform any web-ui test file. Run sync once before the suite. */
export default function setup(): () => void {
  execFileSync('pnpm', ['exec', 'svelte-kit', 'sync'], {
    cwd: resolve('packages/web-ui'),
    stdio: 'inherit',
  });

  // One temp root for this run, so a fixture that forgets to remove its directory leaks into a
  // directory that goes away instead of into the shared `/tmp`. See `test-run-tmpdir.ts` for why
  // this is a redirect rather than a helper the test files call.
  const runRoot = redirectTmpdirForRun();

  return () => {
    const outcome = summariseRunRoot(runRoot);
    // Printed, because a number nobody sees is not a measurement: this is how many directories
    // the suite left behind, and it is meant to go DOWN as fixtures are fixed at the source.
    console.error(
      `test temp root (${outcome.state}): ${String(outcome.entries)} ` +
        `entr${outcome.entries === 1 ? 'y' : 'ies'} left behind`,
    );
    // ⛔ And `failed` THROWS, which fails the run — measured: a throw here does reach the exit
    // code. The first version only PRINTED "AND THE ROOT SURVIVED", which made this file a claim
    // rather than a mechanism: the one state in which the redirect has not stopped the leak would
    // be the one state nothing acts on. `absent` deliberately does not throw — a root that is
    // already gone leaks nothing.
    if (outcome.state === 'failed') {
      throw new Error(
        `test temp root survived at ${runRoot} — it could not be removed (${outcome.reason}). ` +
          `Every entry under it is now leaked into the shared temp directory.`,
      );
    }
  };
}
